#!/usr/bin/env bash
set -euf -o pipefail

node_modules/.bin/sanctuary-lint "$@"

cp README.md README.md.orig
trap 'mv README.md.orig README.md' EXIT

VERSION=0.0.0 PREVIOUS_VERSION=0.0.0 node_modules/.bin/sanctuary-generate-readme

node_modules/.bin/eslint --config eslint/es6.js -- README.md eslint
