#!/usr/bin/env bash
set -euf -o pipefail

node_modules/.bin/c8 \
  --check-coverage \
  --100 \
  --reporter text \
  --reporter html \
  --include index.js \
  node_modules/.bin/oletus -- test/index.js test/module.js
